### ISSUE TITLE
Further Extend Ion Schema

### ISSUE THREAD

**Issue by hampusnasstrom** [FAIRmat-NFDI/nomad-perovskite-solar-cells-database#25]
- [x] Query Ions from abbreviation in `PerovskiteIonComponent` normalize method
- [ ] Create new Ion if none is referenced in `PerovskiteIonComponent` normalize method
- [x] Create an app for Ions and for Compositions
- [x] Create a parser to create `Ion` entities from excel file (most importantly import once from existing excel file)
- [ ] Create a python function for querying and exporting a `PerovskiteCompositon` as a `json` with the ion references resolved in place and the nomad specific information removed
- [ ] Create an example jupyter notebook that queries `PerovskiteComposition` and `Ion` entities and uses the function above to export them
- [ ] Replace/extend the `PerovskiteSolarCell.perovskite` subsection with `PerovskiteComposition`

**Comment by Pepe-Marquez** [comment]
Hi @jesperkemist, @hampusnasstrom and @lauri-codes. These are some tasks that we need to complete to have the ions database in NOMAD to have a complete story for the paper. @hampusnasstrom, feel free to edit this issue as you need as most of the tasks are on your end. 

### Fundamentals

- [ ]  write JSON Schema based on json file from Jesper
- [ ]  check changes with Jesper's new json file
- [ ]  Search app for the Ions
  -   abbreviation
  -   periodic table
  -   iupac names
  -   ion_type

- [ ] Support parent class quantities in the search app @lauri-codes 
- [ ] Introduce a conformer calculator with rdkit
- [ ] docs

  -   Instructions that also go to the supporting information on:
    -   how to add a new cation
    -   how to create a new composition
    -   how to retrieve the data with the API
    -   validate against a json schema

- [ ] parsing the database
- [ ] merge branch perovskite composition in perovskite database main plugin
- [ ] generate figures for the paper

  - Screenshot of the app
  - Screenshot of the cation entry overview with export to cif, xyz ...

### Extras

- [ ] Introduce a charge balance validator in perovskite composition in NOMAD
    - charge_balanced boolean that triggers the normalizer.
 - pyrovskite package notebook example?

- [ ] Calculate geometrical factors
 - geometrical factors in the app

**Comment by hampusnasstrom** [comment]
I added the json schemas now: https://github.com/Jesperkemist/Perovskite_composition/pull/2
and also updated the nomad classes to match: https://github.com/FAIRmat-NFDI/nomad-perovskite-solar-cells-database/commit/f4269ebfd4bb0b9495b486731aa8936800882d7d
