### ISSUE TITLE
Please make pytest optional

### ISSUE THREAD

**Issue by TLCFEM** [FAIRmat-NFDI/nomad-perovskite-solar-cells-database#6]
Please make pytest optional, and other small things. See attached patch.
[Patch.patch.txt](https://github.com/FAIRmat-NFDI/nomad-perovskite-solar-cells-database/files/14564673/Patch.patch.txt)

**Comment by Pepe-Marquez** [comment]
Yaru, at some point we need to align this plugin more towards the latest version of our example plugins. I think Lauri is preparing something new, but if this is not the case we can just update it to match the current example here: https://github.com/nomad-coe/nomad-schema-plugin-example

**Comment by yaruwangway** [comment]
ok! @Pepe-Marquez
